version: "3"
services:
  frontend:
    build: ./front   # フロントエンドのDockerfileの場所
    ports:
      - "3000:3000"        # フロントエンドのポートマッピング
    volumes:
      - ./front:/usr/src/app

  backend:
    build: ./back    # バックエンドのDockerfileの場所
    ports:
      - "8000:8000"      # バックエンドのポートマッピング
    volumes:
      - ./back:/app
